import "./globals.css";
import {ThemeProvider} from "@/components/theme/Theme-Provider";

export const metadata = {
    title: "Rintaro",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="fr">
            <body>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange>
                    {children}
            </ThemeProvider>
            </body>
        </html>
    );
}